In [12]:
# Series
import pandas as pd

serie = pd.Series([1,2,3],index=["first","second","last"])

print(serie.loc["first"])

1

In [20]:
# dataframe
df = pd.DataFrame({
    "math":[10,20,15],
    "arabic":[10,20,15],
    "bio":[10,20,15]
})

df_2 = pd.DataFrame([
    [10,10,10],
    [20,20,20],
    [15,15,15]
],columns=["math","arabic","bio"])

df

   math  arabic  bio
0    10      10   10
1    20      20   20
2    15      15   15

In [21]:
# first 5 rows
df.head()

   math  arabic  bio
0    10      10   10
1    20      20   20
2    15      15   15

In [23]:
# last 5 rows
df.tail()

   math  arabic  bio
0    10      10   10
1    20      20   20
2    15      15   15

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   math    3 non-null      int64
 1   arabic  3 non-null      int64
 2   bio     3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

In [26]:
# get a single column
df["math"]

0    10
1    20
2    15
Name: math, dtype: int64

In [27]:
# get two columns dataframe
df[["math","bio"]]

   math  bio
0    10   10
1    20   20
2    15   15

In [37]:
# row access
df.loc[0,["math","bio"]] # access by label

math    10
bio     10
Name: 0, dtype: int64

In [41]:
# row access by index
df.iloc[0:2,0:2]

   math  arabic
0    10      10
1    20      20

In [43]:
# boolean indexing
df[df["math"]<=15]

   math  arabic  bio
0    10      10   10
2    15      15   15

In [44]:
df[df['math'].isin([15,10])]

   math  arabic  bio
0    10      10   10
2    15      15   15

In [45]:
df['total'] = 5000

In [48]:
# drop a column
df.drop("total",axis=1)

   math  arabic  bio
0    10      10   10
1    20      20   20
2    15      15   15

In [51]:
df = df.rename(columns={'math': 'mathematics'})

In [52]:
df

   mathematics  arabic  bio  total
0           10      10   10   5000
1           20      20   20   5000
2           15      15   15   5000

In [61]:
df.mean()

mathematics      15.0
arabic           15.0
bio              15.0
total          5000.0
dtype: float64

In [64]:
df['rank'] = df['bio'].rank()
df

   mathematics  arabic  ...  total  rank
0           10      10  ...   5000   1.0
1           20      20  ...   5000   3.0
2           15      15  ...   5000   2.0

[3 rows x 5 columns]

In [71]:
df.iloc[1,2] = 10 
df.groupby("bio")["arabic"].mean()

bio
10    15.0
15    15.0
Name: arabic, dtype: float64

In [72]:
df.groupby('bio').agg({
 'mathematics': ['mean', 'sum', 'count'],
 'arabic': 'mean'
})

    mathematics           arabic
           mean sum count   mean
bio
10         15.0  30     2   15.0
15         15.0  15     1   15.0